# Generated by Django 4.1.7 on 2023-03-06 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now=True)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\\t)'), ('|', 'Pipe (|)')], default=',', help_text='Select the character used to separate columns in CSV files.', max_length=2)),
                ('column_characters', models.CharField(choices=[('"', 'Double-quote (")'), (';', 'Semicolon (;)'), (':', 'Colon (:)'), ('^', 'Caret (^)'), ('~', 'Tilde (~)')], default='"', help_text='Select the character used to separate strings in CSV files.', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now=True)),
                ('csv', models.FileField(upload_to='csv')),
                ('status', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='authentication.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('full_name', 'Full Name'), ('job', 'Job'), ('email', 'Email'), ('domain_name', 'Domain Name'), ('phone_number', 'Phone Number'), ('company_name', 'Company Name'), ('text', 'Text'), ('integer', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=100)),
                ('range_start', models.IntegerField(blank=True, null=True)),
                ('range_end', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.schema')),
            ],
        ),
    ]
